#DO NOT CHANGE CONFIG VERSION LINE
configVersion: 1

#Max distance before applying modifiers
maxDistance: 2000

#Cost per block traveled before applying modifiers
#Cost is always rounded up to nearest larger integer
costPerBlockTraveled: 1

baseMaxFuel: 15000

constructionBlocks:
  - STONE_BRICKS
  - CRACKED_STONE_BRICKS
  - MOSSY_STONE_BRICKS

secondaryConstructionBlocks:
  - STONE_SLAB
  - STONE_BRICK_SLAB

blockModifiers:
  IRON_BLOCK:
    cost: 1.2
    distance: 1.4
  EMERALD_BLOCK:
    cost: 1.1
    distance: 4
  GOLDEN_BLOCK:
    cost: 1.2
    distance: 6
  DIAMOND_BLOCK:
    cost: 1.4
    distance: 12

fuel:
  IRON_INGOT:
    fuelValue: 400
  EMERALD:
    fuelValue: 2100
  GOLD_INGOT:
    fuelValue: 4800
  DIAMOND:
    fuelValue: 14000


