#DO NOT CHANGE CONFIG VERSION LINE
configVersion: 1

#Max distance before applying modifiers
maxDistance: 2000

#Cost per block traveled before applying modifiers
#Cost is always rounded up to nearest larger integer
costPerBlockTraveled: 2

baseMaxFuel: 22000

constructionBlocks:
  - STONE_BRICKS
  - CRACKED_STONE_BRICKS
  - MOSSY_STONE_BRICKS

secondaryConstructionBlocks:
  - STONE_SLAB
  - STONE_BRICK_SLAB
  - SMOOTH_STONE_SLAB

blockModifiers:
  IRON_BLOCK:
    cost: 0.82
    distance: 0.85
  EMERALD_BLOCK:
    cost: 0.8
    distance: 0.9
  GOLD_BLOCK:
    cost: 1.12
    distance: 1.25
  DIAMOND_BLOCK:
    cost: 1.3
    distance: 1.6

fuel:
  IRON_INGOT:
    fuelValue: 400
  EMERALD:
    fuelValue: 2100
  GOLD_INGOT:
    fuelValue: 4800
  DIAMOND:
    fuelValue: 14000


