name: TeleportStructures
version: ${project.version}
main: cz.cuni.mff.rodd.teleportstructures.TeleportStructures
api-version: 1.13
authors: [rodd]
description: Teleporter structures
commands:
  telestruct:
    description: Main command for TeleporterStructures
    usage: /<command> [subcommand]
permissions:
  teleportstructures.breaksign:
    default: op
  teleportstructures.genstruct:
    default: op
  teleportstructures.changereqfuel:
    default: op
