name: TeleportStructures
version: ${project.version}
main: cz.cuni.mff.rodd.teleportstructures.Teleportstructures
api-version: 1.13
authors: [rodd]
description: Teleporter structures
permissions:
  teleportstructures.breaksign:
    default: op
